basePath: /api
definitions:
  models.Map:
    additionalProperties: {}
    type: object
  models.Message:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/models.Map'
      description:
        type: string
      message:
        type: string
      recipients:
        items:
          type: integer
        type: array
      url:
        type: string
    required:
    - code
    - data
    - description
    - message
    - recipients
    - url
    type: object
  models.MessageModel:
    properties:
      message:
        type: string
    type: object
  models.PushService:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - ServiceAPNS
    - ServiceFCM
    - ServiceMipush
  models.PushToken:
    properties:
      created_at:
        type: string
      device_id:
        maxLength: 64
        type: string
      package_name:
        type: string
      service:
        $ref: '#/definitions/models.PushService'
      token:
        maxLength: 64
        type: string
      updated_at:
        type: string
      user_id:
        description: not required
        type: integer
    required:
    - device_id
    - token
    type: object
  token.DeleteModel:
    properties:
      device_id:
        maxLength: 64
        type: string
    type: object
info:
  contact:
    email: dev@fduhole.com
    name: Maintainer OpenTreeHole
  description: This is a notification microservice.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Notification Center
  version: 2.0.0
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageModel'
  /callback/mipush:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Mipush Callback
      tags:
      - Callback
  /messages:
    post:
      description: Send to multiple recipients and save to db, admin only.
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/models.Message'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Message'
      summary: Send a message
      tags:
      - Message
  /users/push-tokens:
    delete:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/token.DeleteModel'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete the token of a user's certain device
      tags:
      - Token
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PushToken'
            type: array
      summary: List Tokens of a User
      tags:
      - Token
    post:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/models.PushToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PushToken'
      summary: Add Token of a User
      tags:
      - Token
  /users/push-tokens/_all:
    delete:
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete all tokens of a user
      tags:
      - Token
swagger: "2.0"
